export const fetchRaceBugOracle = [
  "render:selection-B:selection=B",
  "effect_start:effect-B:requestId=request-B-1,selection=B",
  "async_start:request-B-1:delayMs=1200,requestId=request-B-1,selection=B",
  "render:selection-C:selection=C",
  "effect_start:effect-C:requestId=request-C-2,selection=C",
  "async_start:request-C-2:delayMs=200,requestId=request-C-2,selection=C",
  "async_resolve:request-C-2:requestId=request-C-2,selection=C",
  "state_write:todo-C:requestId=request-C-2,selection=C",
  "async_resolve:request-B-1:requestId=request-B-1,selection=B",
  "stale_write:todo-B:requestId=request-B-1,selection=B",
  "invariant_fail:latest-request-wins",
];

export const fetchRaceFixOracle = [
  "render:selection-B:selection=B",
  "effect_start:effect-B:requestId=request-B-1,selection=B",
  "async_start:request-B-1:delayMs=1200,requestId=request-B-1,selection=B",
  "render:selection-C:selection=C",
  "cleanup:effect-B:requestId=request-B-1,selection=B",
  "abort:request-B-1:requestId=request-B-1,selection=B",
  "effect_start:effect-C:requestId=request-C-2,selection=C",
  "async_start:request-C-2:delayMs=200,requestId=request-C-2,selection=C",
  "async_resolve:request-C-2:requestId=request-C-2,selection=C",
  "state_write:todo-C:requestId=request-C-2,selection=C",
  "invariant_pass:latest-request-wins",
];

export const fetchRaceDistractorOracle = [
  "render:selection-B:selection=B",
  "effect_start:effect-B:requestId=request-B-1,selection=B",
  "async_start:request-B-1:delayMs=1200,requestId=request-B-1,selection=B",
  "loading_change:loading-B:loading=true,requestId=request-B-1,selection=B",
  "render:selection-C:selection=C",
  "effect_start:effect-C:requestId=request-C-2,selection=C",
  "async_start:request-C-2:delayMs=200,requestId=request-C-2,selection=C",
  "loading_change:loading-C:loading=true,requestId=request-C-2,selection=C",
  "async_resolve:request-C-2:requestId=request-C-2,selection=C",
  "state_write:todo-C:requestId=request-C-2,selection=C",
  "loading_change:loading-C:loading=false,requestId=request-C-2,selection=C",
  "async_resolve:request-B-1:requestId=request-B-1,selection=B",
  "stale_write:todo-B:requestId=request-B-1,selection=B",
  "loading_change:loading-B:loading=false,requestId=request-B-1,selection=B",
  "invariant_fail:latest-request-wins",
];
